'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace TerroristInfoService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TerroristCatalog", [Namespace]:="http://schemas.datacontract.org/2004/07/FedsfmPortal.Services.TerroristInfo"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TerroristCatalog
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdDbfField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdDocField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdNewXmlField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTerroristCatalogField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdXmlField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsActiveField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TerroristCatalogDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TerroristCatalogNumberField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdDbf() As System.Nullable(Of System.Guid)
            Get
                Return Me.IdDbfField
            End Get
            Set
                If (Me.IdDbfField.Equals(value) <> true) Then
                    Me.IdDbfField = value
                    Me.RaisePropertyChanged("IdDbf")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdDoc() As System.Nullable(Of System.Guid)
            Get
                Return Me.IdDocField
            End Get
            Set
                If (Me.IdDocField.Equals(value) <> true) Then
                    Me.IdDocField = value
                    Me.RaisePropertyChanged("IdDoc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdNewXml() As System.Nullable(Of System.Guid)
            Get
                Return Me.IdNewXmlField
            End Get
            Set
                If (Me.IdNewXmlField.Equals(value) <> true) Then
                    Me.IdNewXmlField = value
                    Me.RaisePropertyChanged("IdNewXml")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTerroristCatalog() As Long
            Get
                Return Me.IdTerroristCatalogField
            End Get
            Set
                If (Me.IdTerroristCatalogField.Equals(value) <> true) Then
                    Me.IdTerroristCatalogField = value
                    Me.RaisePropertyChanged("IdTerroristCatalog")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdXml() As System.Nullable(Of System.Guid)
            Get
                Return Me.IdXmlField
            End Get
            Set
                If (Me.IdXmlField.Equals(value) <> true) Then
                    Me.IdXmlField = value
                    Me.RaisePropertyChanged("IdXml")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsActive() As Boolean
            Get
                Return Me.IsActiveField
            End Get
            Set
                If (Me.IsActiveField.Equals(value) <> true) Then
                    Me.IsActiveField = value
                    Me.RaisePropertyChanged("IsActive")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TerroristCatalogDate() As Date
            Get
                Return Me.TerroristCatalogDateField
            End Get
            Set
                If (Me.TerroristCatalogDateField.Equals(value) <> true) Then
                    Me.TerroristCatalogDateField = value
                    Me.RaisePropertyChanged("TerroristCatalogDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TerroristCatalogNumber() As String
            Get
                Return Me.TerroristCatalogNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TerroristCatalogNumberField, value) <> true) Then
                    Me.TerroristCatalogNumberField = value
                    Me.RaisePropertyChanged("TerroristCatalogNumber")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PageBase", [Namespace]:="http://schemas.datacontract.org/2004/07/FedsfmPortal.Services.TerroristInfo"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(TerroristInfoService.TerroristCatalogPage))>  _
    Partial Public Class PageBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageIndexField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageSizeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PagesTotalField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RecordsTotalField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageIndex() As Integer
            Get
                Return Me.PageIndexField
            End Get
            Set
                If (Me.PageIndexField.Equals(value) <> true) Then
                    Me.PageIndexField = value
                    Me.RaisePropertyChanged("PageIndex")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageSize() As Integer
            Get
                Return Me.PageSizeField
            End Get
            Set
                If (Me.PageSizeField.Equals(value) <> true) Then
                    Me.PageSizeField = value
                    Me.RaisePropertyChanged("PageSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PagesTotal() As Integer
            Get
                Return Me.PagesTotalField
            End Get
            Set
                If (Me.PagesTotalField.Equals(value) <> true) Then
                    Me.PagesTotalField = value
                    Me.RaisePropertyChanged("PagesTotal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RecordsTotal() As Integer
            Get
                Return Me.RecordsTotalField
            End Get
            Set
                If (Me.RecordsTotalField.Equals(value) <> true) Then
                    Me.RecordsTotalField = value
                    Me.RaisePropertyChanged("RecordsTotal")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TerroristCatalogPage", [Namespace]:="http://schemas.datacontract.org/2004/07/FedsfmPortal.Services.TerroristInfo"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TerroristCatalogPage
        Inherits TerroristInfoService.PageBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TerroristCatalogsField() As TerroristInfoService.TerroristCatalog
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TerroristCatalogs() As TerroristInfoService.TerroristCatalog()
            Get
                Return Me.TerroristCatalogsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TerroristCatalogsField, value) <> true) Then
                    Me.TerroristCatalogsField = value
                    Me.RaisePropertyChanged("TerroristCatalogs")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PortalFile", [Namespace]:="http://schemas.datacontract.org/2004/07/FedsfmPortal.Services.TerroristInfo"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PortalFile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreateDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileDataField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileLengthField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdFileField As System.Guid
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreateDate() As Date
            Get
                Return Me.CreateDateField
            End Get
            Set
                If (Me.CreateDateField.Equals(value) <> true) Then
                    Me.CreateDateField = value
                    Me.RaisePropertyChanged("CreateDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileData() As Byte()
            Get
                Return Me.FileDataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileDataField, value) <> true) Then
                    Me.FileDataField = value
                    Me.RaisePropertyChanged("FileData")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileDate() As Date
            Get
                Return Me.FileDateField
            End Get
            Set
                If (Me.FileDateField.Equals(value) <> true) Then
                    Me.FileDateField = value
                    Me.RaisePropertyChanged("FileDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileLength() As Integer
            Get
                Return Me.FileLengthField
            End Get
            Set
                If (Me.FileLengthField.Equals(value) <> true) Then
                    Me.FileLengthField = value
                    Me.RaisePropertyChanged("FileLength")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileName() As String
            Get
                Return Me.FileNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileNameField, value) <> true) Then
                    Me.FileNameField = value
                    Me.RaisePropertyChanged("FileName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdFile() As System.Guid
            Get
                Return Me.IdFileField
            End Get
            Set
                If (Me.IdFileField.Equals(value) <> true) Then
                    Me.IdFileField = value
                    Me.RaisePropertyChanged("IdFile")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="TerroristInfoService.ITerroristInfoService")>  _
    Public Interface ITerroristInfoService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITerroristInfoService/GetCurrentTerroristCatalog", ReplyAction:="http://tempuri.org/ITerroristInfoService/GetCurrentTerroristCatalogResponse")>  _
        Function GetCurrentTerroristCatalog() As TerroristInfoService.TerroristCatalog
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITerroristInfoService/GetCurrentTerroristCatalog", ReplyAction:="http://tempuri.org/ITerroristInfoService/GetCurrentTerroristCatalogResponse")>  _
        Function GetCurrentTerroristCatalogAsync() As System.Threading.Tasks.Task(Of TerroristInfoService.TerroristCatalog)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITerroristInfoService/GetTerroristCatalogs", ReplyAction:="http://tempuri.org/ITerroristInfoService/GetTerroristCatalogsResponse")>  _
        Function GetTerroristCatalogs(ByVal pageIndex As Integer) As TerroristInfoService.TerroristCatalogPage
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITerroristInfoService/GetTerroristCatalogs", ReplyAction:="http://tempuri.org/ITerroristInfoService/GetTerroristCatalogsResponse")>  _
        Function GetTerroristCatalogsAsync(ByVal pageIndex As Integer) As System.Threading.Tasks.Task(Of TerroristInfoService.TerroristCatalogPage)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITerroristInfoService/GetFile", ReplyAction:="http://tempuri.org/ITerroristInfoService/GetFileResponse")>  _
        Function GetFile(ByVal fileId As System.Guid) As TerroristInfoService.PortalFile
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITerroristInfoService/GetFile", ReplyAction:="http://tempuri.org/ITerroristInfoService/GetFileResponse")>  _
        Function GetFileAsync(ByVal fileId As System.Guid) As System.Threading.Tasks.Task(Of TerroristInfoService.PortalFile)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ITerroristInfoServiceChannel
        Inherits TerroristInfoService.ITerroristInfoService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TerroristInfoServiceClient
        Inherits System.ServiceModel.ClientBase(Of TerroristInfoService.ITerroristInfoService)
        Implements TerroristInfoService.ITerroristInfoService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetCurrentTerroristCatalog() As TerroristInfoService.TerroristCatalog Implements TerroristInfoService.ITerroristInfoService.GetCurrentTerroristCatalog
            Return MyBase.Channel.GetCurrentTerroristCatalog
        End Function
        
        Public Function GetCurrentTerroristCatalogAsync() As System.Threading.Tasks.Task(Of TerroristInfoService.TerroristCatalog) Implements TerroristInfoService.ITerroristInfoService.GetCurrentTerroristCatalogAsync
            Return MyBase.Channel.GetCurrentTerroristCatalogAsync
        End Function
        
        Public Function GetTerroristCatalogs(ByVal pageIndex As Integer) As TerroristInfoService.TerroristCatalogPage Implements TerroristInfoService.ITerroristInfoService.GetTerroristCatalogs
            Return MyBase.Channel.GetTerroristCatalogs(pageIndex)
        End Function
        
        Public Function GetTerroristCatalogsAsync(ByVal pageIndex As Integer) As System.Threading.Tasks.Task(Of TerroristInfoService.TerroristCatalogPage) Implements TerroristInfoService.ITerroristInfoService.GetTerroristCatalogsAsync
            Return MyBase.Channel.GetTerroristCatalogsAsync(pageIndex)
        End Function
        
        Public Function GetFile(ByVal fileId As System.Guid) As TerroristInfoService.PortalFile Implements TerroristInfoService.ITerroristInfoService.GetFile
            Return MyBase.Channel.GetFile(fileId)
        End Function
        
        Public Function GetFileAsync(ByVal fileId As System.Guid) As System.Threading.Tasks.Task(Of TerroristInfoService.PortalFile) Implements TerroristInfoService.ITerroristInfoService.GetFileAsync
            Return MyBase.Channel.GetFileAsync(fileId)
        End Function
    End Class
End Namespace
